# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Prisma Compute
        uses: prisma/project-compute/github-action@main
        with:
          api-token: ${{ secrets.PRISMA_API_TOKEN }}
          compute-service-id: cmq9e8dtr0yv4zofby0avf5tn
